 # Create the new instance template
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: create-instance-template
  args:
    - compute
    - instance-templates
    - create-with-container
    - ${_SERVICE_NAME}-instance-template-$_ENV-$SHORT_SHA
    - --machine-type=e2-small
    - --boot-disk-size=10GB
    - --boot-disk-type=pd-balanced
    - --boot-disk-device-name=${_SERVICE_NAME}-instance-template
    - --tags=web,http-server,https-server
    - --region=us-central1
    - --service-account=${_SERVICE_ACCOUNT}
    - --container-image
    - gcr.io/proyectofinal1-455100/github.com/f-munozg/${_CONTAINER_IMAGE}:latest
    
 # Update the managed instance group


- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c','gcloud compute instance-groups managed rolling-action start-update ${_SERVICE_NAME}-instance-group --version=template=${_SERVICE_NAME}-instance-template-$_ENV-$SHORT_SHA --zone=${_SERVICE_ZONE} --max-unavailable=0'] 
  
options:
 logging: CLOUD_LOGGING_ONLY