name: Test_Coverage
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches: 
      - develop
      - main
jobs:
  test_web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Save test variable to env variable
        run: echo "IS_UNIT_TEST=1" >> $GITHUB_ENV
      - name: Init virtual environment
        working-directory: ./customers
        run: python -m venv ./venv
      - name: Enable environment
        working-directory: ./customers
        run: source ./venv/bin/activate
      - name: Install dependencies
        working-directory: ./customers
        run: pip install -r requirements.txt
      - name: Run unit tests
        working-directory: ./customers
        run: pytest --cov=. -v -s --cov-fail-under=80